FROM node:22-alpine AS base
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --only=production
COPY . .

FROM base AS test
RUN npm ci
COPY test/vitest/vitest.silvermoon* ./
RUN npm test

FROM base AS production
EXPOSE 18791
CMD ["node", "main.js"]
